name: hexlet-check

on:
  push:
    branches:
      - master

jobs:
  super-lint:
    name: Lint code base
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hexlet project check
        uses: hexlet/project-action@release
      - name: Run Super-Linter
        usese: github/super-linter@3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
